---
title: "Exploratory Data Analysis"
author: ""
date: ""
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r, include=FALSE}
library(tidyverse)
library(patchwork)
library(plotly)
```

# Exploratory Data Analysis

# PM2.5 
Plot comparisons by year/borough. 

```{r}
library(tidyverse)
library(rvest)
library(readxl)
library(plotly)
library(flexdashboard)
library(sf)
library(shiny)
library(leaflet)
library(scales)
```

```{r}
particulate_matter = 
  read_csv("data/Air_Quality_20231208.csv")
```

```{r}
tidy_analysis_pm = 
  particulate_matter |>
  janitor::clean_names() |>
    mutate(
    unique_id = as.character(unique_id),
    indicator_id = as.character(indicator_id),
    geo_join_id = as.character(geo_join_id)) |>
  filter(name == "Fine particles (PM 2.5)") |>
  filter(time_period %in% c("Annual Average 2016", "Annual Average 2017",
                            "Annual Average 2018", "Annual Average 2019",
                            "Annual Average 2020", "Annual Average 2021")) |>
  filter(geo_type_name == "Borough") |>
  select(-unique_id, -indicator_id, -start_date) |>
    rename(borough = geo_place_name) |>
  mutate(
    period = case_when(
      time_period %in% c("Annual Average 2016", "Annual Average 2017", "Annual Average 2018") ~ "2016-2018",
      time_period %in% c("Annual Average 2019", "Annual Average 2020", "Annual Average 2021") ~ "2019-2021"
    )
  ) |>
  group_by(borough, period) |>
  summarize(
    average_pm2.5 = mean(data_value, na.rm = TRUE),
    .groups = "drop"
  ) |>
  pivot_wider(
    names_from = period,
    values_from = average_pm2.5,
    names_prefix = "avg_pm2.5_"
  )
```

```{r}
tidy_analysis_pm |>
  pivot_longer(cols = -borough, names_to = "Year_Group", values_to = "PM2.5") |> 
  mutate(borough = factor(borough, levels = unique(borough[order(PM2.5)]))) |> 
  ggplot(aes(x = borough, y = PM2.5, fill = Year_Group)) +
  geom_bar(position = "dodge", stat = "identity") +
   labs(
    title = "Average PM2.5 Levels by Borough (2016-2018 vs 2019-2021)",
    x = "Borough",
    y = "PM2.5 Values",
    fill = "Year Group"
  ) 
```

make knitr chart that shows with in numbers differences between years 

Show map of PM2.5 levels per UH42 index across years. 

```{r}
geography = 
  read_excel("data/geoid_borough_name_nyc.xlsx") |>
  rename(geo_join_id = ID) |>
  mutate(geo_join_id = 
           as.character(geo_join_id))
```

```{r}
particulate_matter = 
  read_csv("data/Air_Quality_20231208.csv")
```

```{r}
tidy_uhf42_pm = 
  particulate_matter |>
  janitor::clean_names() |>
    mutate(
    unique_id = as.character(unique_id),
    indicator_id = as.character(indicator_id),
    geo_join_id = as.character(geo_join_id)) |>
  filter(name == "Fine particles (PM 2.5)") |>
  filter(time_period %in% c("Annual Average 2016", "Annual Average 2017",
                            "Annual Average 2018", "Annual Average 2019",
                            "Annual Average 2020", "Annual Average 2021")) |>
  filter(geo_type_name == "UHF42") |>
  select(-unique_id, -indicator_id, -start_date) |>
  mutate(
    period = case_when(
      time_period %in% c("Annual Average 2016", "Annual Average 2017", "Annual Average 2018") ~ "2016_2018",
      time_period %in% c("Annual Average 2019", "Annual Average 2020", "Annual Average 2021") ~ "2019_2021"
    )
  ) |>
  group_by(geo_place_name, geo_join_id, period) |>
  summarize(
    average_pm2.5 = mean(data_value, na.rm = TRUE),
    .groups = "drop"
  ) |>
  pivot_wider(
    names_from = period,
    values_from = average_pm2.5,
    names_prefix = "avg_pm2.5_"
  ) 
```

```{r}
uhf42_map <- st_read("data/UHF_42_DOHMH_2009.shp") 

tidy_uhf42_pm <- 
  tidy_uhf42_pm |>
  rename(UHFCODE = geo_join_id) |>
  mutate(
    UHFCODE = as.double(UHFCODE))
```


```{r}
map_uhf42 <- 
  uhf42_map |>
  left_join(tidy_uhf42_pm, by = "UHFCODE") 
```



# Greenspace

