---
title: "Report"
author: ""
date: ""
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Motivation

Children’s health and development is impacted by the surrounding environment, particularly in dense urban environments like New York City (NYC). Poor air quality due to urban air pollution can influence and have long-term consequences for child and adolescent respiratory health. The challenges of urban environmental health are further complicated by climate change, particularly through the urban heat island effect, which can increase the risk of heat-related illnesses (Heaviside et al., 2017). Limited research shows that elevated temperatures due to the urban heat island effect are associated with increased emergency department (ED) visits among children (Sheffield et al., 2018). 

These health outcomes may be influenced by the availability of green spaces, which can help filter air pollutants and provide cooler areas for shelter from heat. Importantly, environmental health risks disproportionately affect children from low-income neighborhoods and communities of color, where there is often limited access to green spaces and higher exposure to environmental stressors (Corburn et al., 2006).

Through this project, we aim to investigate how these interconnected environmental determinants- air quality, green space availability, and urban heat patterns - vary across NYC boroughs and their potential associations with children’s health, specifically focusing on ED asthma admissions and hospitalizations. We believe that understanding these relationships is crucial for informing urban planning policies and public health initiatives aimed at improving children’s health in New York City.

# Initial Questions

#### 1. How do pediatric asthma outcomes and environmental factors vary across NYC?

* How do asthma ED admission and hospitalization rates vary across NYC boroughs between 2016-2018 and 2019-2021?
* What is the distribution of environmental factors (PM2.5, temperature, greenspace) across NYC during these periods?

#### 2. What relationships emerge between environmental factors and pediatric asthma rates across NYC?

* Do areas with higher ED admission and hospitalization rates align with particular environmental patterns?
* Are there geographic clusters where both environmental inequities and higher asthma rates persist across time periods?
* What are the estimated associations between environmental factors (PM2.5, temperature, greenspace) and pediatric asthma ED rates, accounting for borough-level and temporal variation?

# Data

# Exploratory Analysis

# Regression Analysis

# References

Corburn, J., Osleeb, J., & Porter, M. (2006). Urban asthma and the neighbourhood environment in New York City. Health & place, 12(2), 167-179.

Heaviside, C., Macintyre, H., & Vardoulakis, S. (2017). The urban heat island: implications for health in a changing environment. Current environmental health reports, 4, 296-305.

Sheffield, P. E., Herrera, M. T., Kinnee, E. J., & Clougherty, J. E. (2018). Not so little differences: variation in hot weather risk to young children in New York City. Public health, 161, 119–126. https://doi.org/10.1016/j.puhe.2018.06.004


